modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="leveling_pickaxe"
version="1.0"
displayName="Leveling Pickaxe"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="swutm"

[[dependencies.leveling_pickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




